server:
  port: 8085





spring:
  application:
    name: api-board-composition

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true



resilience4j:
  circuitbreaker:
    instances:
      boardFeignClient:
        # ?? ????? ??
        # Closed : ???? ??
        # Open : api-b? ?? ?? ???? ????? ???? "??" ??? ???
        #         "??" ????? ???? ??? ?? ?? ?? ??
        #         ?? ??? ??? "???" ??? ??
        # Half-Open : api-b? ??? ???? ?? ?? ??? ??

        minimumNumberOfCalls: 5   # ?? 5? ??? ??? ??? ???? ???
        slidingWindowSize: 10    # ?? 10? ?? ?
        failureRateThreshold: 50  # 50% ?? ???? Open ??? ??
        waitDurationInOpenState: 30s  # Open ??? 30??? ??, 30? ? Half-Open??? ??
        permittedNumberOfCallsInHalfOpenState: 2  # Half-Open ???? 2? ???? Closed ??? ??