server:
  port: 8082
spring:
  application:
    name: api-board-query

  kafka:
    bootstrap-servers: 10.10.10.40:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      group-id: abcd-group-1 # ?? ???? ???? ???
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false # ????? ?? ??(??? ??)? ????? ??

